variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: juliagpu/cuda:10.1-cudnn7-cutensor1-devel-ubuntu18.04

test:v1.3:
  extends:
    - .julia:1.3
    - .test
  variables:
    CI_VERSION_TAG: 'v1.3'

test:dev:
  extends:
    - .julia:nightly
    - .test
  allow_failure: true
  variables:
    CI_VERSION_TAG: 'v1.4'

coverage:
  stage: post
  extends:
    - .julia:1.2
  script:
    - julia -e 'using Pkg;
                Pkg.instantiate();
                Pkg.add("Coverage")'
    - julia -e 'using Coverage;
                cl, tl = get_summary(process_folder());
                println("(", cl/tl*100, "%) covered")'
  coverage: '/\(\d+.\d+\%\) covered/'

# pages:
#   stage: deploy
#   script:
#     - mv docs/build public
#   artifacts:
#     paths:
#     - public
#   only:
#     - master
